var zhongdong6guo = [
  {
    国家: "JO",
    省: "Jerash Governorate",
    城市: "Jarash",
    区: "Jarash Qasabah District",
  },
  {
    国家: "JO",
    省: "Jerash Governorate",
    城市: "Jarash",
    区: "Mestabah Sub-District",
  },
  {
    国家: "JO",
    省: "Jerash Governorate",
    城市: "Jarash",
    区: "Borma Sub-District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Ma'an Qasabah District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Mraighah Sub-District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Petra District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Shobak Qasabah District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Udhruh Sub-District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Huseiniya District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Iell Sub-District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Jafr Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Faisaliah Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Jrainah Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Madaba Qasabah District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Maeen Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Mlaih Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Areedh Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Dieban District",
  },
  {
    国家: "JO",
    省: "Ajloun Governorate",
    城市: "Ajlun",
    区: "Ajlun Qasabah District",
  },
  {
    国家: "JO",
    省: "Ajloun Governorate",
    城市: "Ajlun",
    区: "Kufranjah District",
  },
  {
    国家: "JO",
    省: "Ajloun Governorate",
    城市: "Ajlun",
    区: "Orjan SubDistrict",
  },
  {
    国家: "JO",
    省: "Ajloun Governorate",
    城市: "Ajlun",
    区: "Sakhrah Sub-District",
  },
  {
    国家: "JO",
    省: "Aqaba Governorate",
    城市: "Al-Aqabah",
    区: "Wadi Araba Sub-District",
  },
  {
    国家: "JO",
    省: "Aqaba Governorate",
    城市: "Al-Aqabah",
    区: "Aqaba Qasabah District",
  },
  {
    国家: "JO",
    省: "Aqaba Governorate",
    城市: "Al-Aqabah",
    区: "Diesah Sub-District",
  },
  {
    国家: "JO",
    省: "Aqaba Governorate",
    城市: "Al-Aqabah",
    区: "Quairah District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Shoonah Janoobiah District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Zayy Sub-District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Ain Albasha District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Al Ardha Sub-District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Dair Alla District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Ira & Yargha Sub-District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Mahes & Fuhais District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Salt Qasabah District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Mazar Janoobee District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Mo'aab Sub-District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Mowjeb Sub-District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Qasr District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Qatraneh District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Aghwar Janoobiyah District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Ayy District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Faqo'e District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Ghawr Almazra'a Sub-District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Karak Qasabah District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Sama Serhan District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Um Al-Jemal Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Um-Elqotain Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Hosha Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Khaldiyah Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Mafraq Qasabah District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Manshiyah Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "North West Badiah District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Rihab Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Rwaished District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Sabha Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Al-Badiah Ash-Shamaliyah District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Bal'ama Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Dair Al Kahaf Sub-District",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Sweileh"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Tareq"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Tla al-Ali",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Wadi As-Seir",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Zahran"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Marj Al Hamam",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Marka"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Na'ur"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Ohud"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Ras al-Ain",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Sahab"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Shafa Badran",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Yarmouk",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al-Muwaqqar",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Badr"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Badr AjJadidah",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Basman"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Husban & Um al Basateen",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Kherbat as-Souk",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Khilda"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Abu Nseir"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Abdali"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Jizah"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Jubeiha",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Madinah",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Muqabalein",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Naser"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Qweismeh",
  },
  {
    国家: "JO",
    省: "Tafilah Governorate",
    城市: "At-Tafilah",
    区: "Bsaira District",
  },
  {
    国家: "JO",
    省: "Tafilah Governorate",
    城市: "At-Tafilah",
    区: "Hasa District",
  },
  {
    国家: "JO",
    省: "Tafilah Governorate",
    城市: "At-Tafilah",
    区: "Tafiela Qasabah District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Azraq Sub-District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Bierain Sub-District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Dhlail Sub-District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Hashemiyah District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Russeifa District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Zarqa Qasabah District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Bani Kinanah Department",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Bani Obeid District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Bayt Ras"
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Irbid Qasabah District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Ramtha District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Taybeh District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Wastiyyah District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Aghwar Shamaliyah District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Al Mazar al Shamali",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Al-Kourah District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "At-Turrah"
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Aydun"
  },











  


  {"国家": "AE","省": "Abu Dhabi","城市": "Al Ruways"},
{"国家": "AE","省": "Abu Dhabi","城市": "Habshan"},
{"国家": "AE","省": "Abu Dhabi","城市": "Al Ardiyah"},
{"国家": "AE","省": "Abu Dhabi","城市": "Sila"},
{"国家": "AE","省": "Abu Dhabi","城市": "Al Dharbaniyah"},
{"国家": "AE","省": "Abu Dhabi","城市": "Suwayhan"},
{"国家": "AE","省": "Abu Dhabi","城市": "Al Dhayd"},
{"国家": "AE","省": "Abu Dhabi","城市": "Al Duss"},
{"国家": "AE","省": "Abu Dhabi","城市": "Al Mafraq"},
{"国家": "AE","省": "Abu Dhabi","城市": "Al Khatem"},
{"国家": "AE","省": "Abu Dhabi","城市": "Al Marfa"},
{"国家": "AE","省": "Dubai","城市": "Dubai Internet City"},
{"国家": "AE","省": "Dubai","城市": "Bur Dubai"},
{"国家": "AE","省": "Dubai","城市": "Mina Sufooh"},
{"国家": "AE","省": "Sharjah","城市": "Hamariya"},
{"国家": "AE","省": "Dubai","城市": "Karama"},
{"国家": "AE","省": "Dubai","城市": "Shandaghah"},
{"国家": "AE","省": "Dubai","城市": "Al Qouz"},
{"国家": "AE","省": "Dubai","城市": "Deira"},
{"国家": "AE","省": "Sharjah","城市": "Al Khashfah"},
{"国家": "AE","省": "Dubai","城市": "Reem Community"},
{"国家": "AE","省": "Dubai","城市": "Dubai"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Al Jazirah"},
{"国家": "AE","省": "Sharjah","城市": "Ramlah"},
{"国家": "AE","省": "Sharjah","城市": "Saabah"},
{"国家": "AE","省": "Dubai","城市": "Jebal Ali"},
{"国家": "AE","省": "Um Al Quiwan","城市": "Um Al Quiwan"},
{"国家": "AE","省": "Fujairah","城市": "Qidfa"},
{"国家": "AE","省": "Sharjah","城市": "Wasit"},
{"国家": "AE","省": "Dubai","城市": "Al Ruwaiya"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Khawr Khuwayr"},
{"国家": "AE","省": "Dubai","城市": "Ganthoot"},
{"国家": "AE","省": "Fujairah","城市": "Kidfa"},
{"国家": "AE","省": "Dubai","城市": "Hatta"},
{"国家": "AE","省": "Fujairah","城市": "Al Hayl"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Al Sha'M"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Khatt"},
{"国家": "AE","省": "Al Ain","城市": "Rima"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Awanat"},
{"国家": "AE","省": "Al Ain","城市": "Al Hayr"},
{"国家": "AE","省": "Fujairah","城市": "Furfar"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Al Hamraniyah"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Sham"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Al Fulayyah"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Al Manamah"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Adhan"},
{"国家": "AE","省": "Abu Dhabi","城市": "Buteen"},
{"国家": "AE","省": "Abu Dhabi","城市": "Al Maqta"},
{"国家": "AE","省": "Abu Dhabi","城市": "Mussafah"},
{"国家": "AE","省": "Abu Dhabi","城市": "Abu Dhabi"},
{"国家": "AE","省": "Abu Dhabi","城市": "Um Al Nar"},
{"国家": "AE","省": "Ajman","城市": "Ajman City"},
{"国家": "AE","省": "Ajman","城市": "Masfut"},
{"国家": "AE","省": "Sharjah","城市": "Al Rafa'ah"},
{"国家": "AE","省": "Sharjah","城市": "Nakheelat"},
{"国家": "AE","省": "Ajman","城市": "Mushrif"},
{"国家": "AE","省": "Fujairah","城市": "Ghurfah"},
{"国家": "AE","省": "Fujairah","城市": "Diba Al Bay'a"},
{"国家": "AE","省": "Fujairah","城市": "Khawr Kalba"},
{"国家": "AE","省": "Ras Al Khaimah","城市": "Al Jazirah Al Hamra"},
{"国家": "AE","省": "Sharjah","城市": "Buteena"},
{"国家": "AE","省": "Sharjah","城市": "Ramaqiya"},
{"国家": "AE","省": "Sharjah","城市": "Kharayan"},

  










{"国家": "QA","省": "Doha","城市": "Al Jasrah"},
{"国家": "QA","省": "Doha","城市": "Al Bidda"},
{"国家": "QA","省": "Doha","城市": "Fereej Mohamed Bin Jasim"},
{"国家": "QA","省": "Doha","城市": "Mushayrib"},
{"国家": "QA","省": "Doha","城市": "Al Najada"},
{"国家": "QA","省": "Doha","城市": "Barahat Al Jufairi"},
{"国家": "QA","省": "Doha","城市": "Fereej Al Asmakh"},
{"国家": "QA","省": "Doha","城市": "Old Al Ghanim"},
{"国家": "QA","省": "Doha","城市": "Al Souq"},
{"国家": "QA","省": "Doha","城市": "Wadi Al Sail"},
{"国家": "QA","省": "Doha","城市": "Rumeilah"},
{"国家": "QA","省": "Doha","城市": "Fereej Abdel Aziz"},
{"国家": "QA","省": "Doha","城市": "Ad Dawhah al Jadidah"},
{"国家": "QA","省": "Doha","城市": "Al Rufaa"},
{"国家": "QA","省": "Doha","城市": "Old Al Hitmi"},
{"国家": "QA","省": "Doha","城市": "As Salatah"},
{"国家": "QA","省": "Doha","城市": "Al Mirqab"},
{"国家": "QA","省": "Doha","城市": "Doha Port"},
{"国家": "QA","省": "Doha","城市": "Fereej Bin Mahmoud"},
{"国家": "QA","省": "Doha","城市": "Rawdat Al Khail"},
{"国家": "QA","省": "Doha","城市": "Fereej Bin Durham"},
{"国家": "QA","省": "Doha","城市": "Al Mansoura"},
{"国家": "QA","省": "Doha","城市": "Najma"},
{"国家": "QA","省": "Doha","城市": "Umm Ghuwailina"},
{"国家": "QA","省": "Doha","城市": "Al Khulaifat"},
{"国家": "QA","省": "Doha","城市": "Ras Abu Aboud"},
{"国家": "QA","省": "Doha","城市": "Duhail"},
{"国家": "QA","省": "Doha","城市": "Umm Lekhba"},
{"国家": "QA","省": "Doha","城市": "Madinat Khalifa North"},
{"国家": "QA","省": "Doha","城市": "Dahl Al Hamam"},
{"国家": "QA","省": "Doha","城市": "Al Markhiya"},
{"国家": "QA","省": "Doha","城市": "Madinat Khalifa South"},
{"国家": "QA","省": "Doha","城市": "Fereej Kulaib"},
{"国家": "QA","省": "Doha","城市": "Al Messila"},
{"国家": "QA","省": "Doha","城市": "Fereej Bin Omran"},
{"国家": "QA","省": "Doha","城市": "New Al Hitmi"},
{"国家": "QA","省": "Doha","城市": "Hamad Medical City"},
{"国家": "QA","省": "Doha","城市": "Al Sadd"},
{"国家": "QA","省": "Doha","城市": "New Al Mirqab"},
{"国家": "QA","省": "Doha","城市": "Fereej Al Nasr"},
{"国家": "QA","省": "Doha","城市": "New Salatah"},
{"国家": "QA","省": "Doha","城市": "Nuaija"},
{"国家": "QA","省": "Doha","城市": "Al Hilal"},
{"国家": "QA","省": "Doha","城市": "Old Airport"},
{"国家": "QA","省": "Doha","城市": "Al Thumama"},
{"国家": "QA","省": "Doha","城市": "Doha International Airport"},
{"国家": "QA","省": "Doha","城市": "Industrial Area"},
{"国家": "QA","省": "Doha","城市": "Al Dafna"},
{"国家": "QA","省": "Doha","城市": "Al Qassar"},
{"国家": "QA","省": "Doha","城市": "Onaiza"},
{"国家": "QA","省": "Doha","城市": "Lejbailat"},
{"国家": "QA","省": "Doha","城市": "Leqtaifiya"},
{"国家": "QA","省": "Doha","城市": "Hazm Al Markhiya"},
{"国家": "QA","省": "Doha","城市": "Jelaiah"},
{"国家": "QA","省": "Doha","城市": "Al Tarfa"},
{"国家": "QA","省": "Doha","城市": "Jeryan Nejaima"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Gharrafa"},
{"国家": "QA","省": "Al Rayyan","城市": "Gharrafat Al Rayyan"},
{"国家": "QA","省": "Al Rayyan","城市": "Izghawa"},
{"国家": "QA","省": "Al Rayyan","城市": "Bani Hajer"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Seej"},
{"国家": "QA","省": "Al Rayyan","城市": "Rawdat Egdaim"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Themaid"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Luqta"},
{"国家": "QA","省": "Al Rayyan","城市": "Lebday"},
{"国家": "QA","省": "Al Rayyan","城市": "Old Al Rayyan"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Shagub"},
{"国家": "QA","省": "Al Rayyan","城市": "Fereej Al Zaeem"},
{"国家": "QA","省": "Al Rayyan","城市": "New Al Rayyan"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Wajbah"},
{"国家": "QA","省": "Al Rayyan","城市": "Muaither"},
{"国家": "QA","省": "Al Rayyan","城市": "Fereej Al Amir"},
{"国家": "QA","省": "Al Rayyan","城市": "Luaib"},
{"国家": "QA","省": "Al Rayyan","城市": "Muraikh"},
{"国家": "QA","省": "Al Rayyan","城市": "Baaya"},
{"国家": "QA","省": "Al Rayyan","城市": "Mehairja"},
{"国家": "QA","省": "Al Rayyan","城市": "Fereej Al Soudan"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Waab"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Aziziya"},
{"国家": "QA","省": "Al Rayyan","城市": "New Fereej Al Ghanim"},
{"国家": "QA","省": "Al Rayyan","城市": "Fereej Al Murra"},
{"国家": "QA","省": "Al Rayyan","城市": "Fereej Al Manaseer"},
{"国家": "QA","省": "Al Rayyan","城市": "Bu Sidra"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Sailiya"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Mearad"},
{"国家": "QA","省": "Al Rayyan","城市": "Fereej Al Asiri"},
{"国家": "QA","省": "Al Rayyan","城市": "New Fereej Al Khulaifat"},
{"国家": "QA","省": "Al Rayyan","城市": "Bu Samra"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Mamoura"},
{"国家": "QA","省": "Al Rayyan","城市": "Abu Hamour"},
{"国家": "QA","省": "Al Rayyan","城市": "Mesaimeer"},
{"国家": "QA","省": "Al Rayyan","城市": "Ain Khaled"},
{"国家": "QA","省": "Al Rayyan","城市": "Mebaireek"},
{"国家": "QA","省": "Al Rayyan","城市": "Al Karaana"},
{"国家": "QA","省": "Al Rayyan","城市": "Abu Samra"},
{"国家": "QA","省": "Al Rayyan","城市": "Sawda Natheel"},
{"国家": "QA","省": "Al Daayen","城市": "Jabal Thuaileb"},
{"国家": "QA","省": "Al Daayen","城市": "Al Kharayej"},
{"国家": "QA","省": "Al Daayen","城市": "Lusail"},
{"国家": "QA","省": "Al Daayen","城市": "Al Egla"},
{"国家": "QA","省": "Al Daayen","城市": "Wadi Al Banat"},
{"国家": "QA","省": "Al Daayen","城市": "Leabaib"},
{"国家": "QA","省": "Al Daayen","城市": "Al Ebb"},
{"国家": "QA","省": "Al Daayen","城市": "Jeryan Jenaihat"},
{"国家": "QA","省": "Al Daayen","城市": "Al Kheesa"},
{"国家": "QA","省": "Al Daayen","城市": "Rawdat Al Hamama"},
{"国家": "QA","省": "Al Daayen","城市": "Wadi Al Wasaah"},
{"国家": "QA","省": "Al Daayen","城市": "Al Sakhama"},





{"国家": "BH","省": "Central Governorate","城市": "A'ali"},
{"国家": "BH","省": "Central Governorate","城市": "Hoarat A'ali"},
{"国家": "BH","省": "Central Governorate","城市": "Ma'ameer"},
{"国家": "BH","省": "Muharraq Governorate","城市": "Muharraq"},
{"国家": "BH","省": "Northern Governorate","城市": "Abu Baham"},
{"国家": "BH","省": "Northern Governorate","城市": "Abu Saiba"},
{"国家": "BH","省": "Capital Governorate","城市": "Al Burhama"},
{"国家": "BH","省": "Muharraq Governorate","城市": "Al Dair"},
{"国家": "BH","省": "Southern Governorate","城市": "Al Dur"},
{"国家": "BH","省": "Central Governorate","城市": "Al Eker"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Hajar"},
{"国家": "BH","省": "Muharraq Governorate","城市": "Al Hidd"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Janabiyah"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Jasra"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Lawzi"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Malikiyah"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Maqsha"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Markh"},
{"国家": "BH","省": "Southern Governorate","城市": "Al Mazrowiah"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Musalla"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Qadam"},
{"国家": "BH","省": "Capital Governorate","城市": "Al Qalah"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Qurayyah"},
{"国家": "BH","省": "Northern Governorate","城市": "Al Safriyah"},
{"国家": "BH","省": "Muharraq Governorate","城市": "Al Sayh"},
{"国家": "BH","省": "Muharraq Governorate","城市": "Arad"},
{"国家": "BH","省": "Southern Governorate","城市": "Askar"},
{"国家": "BH","省": "Southern Governorate","城市": "Awali"},
{"国家": "BH","省": "Northern Governorate","城市": "Bani Jamra"},
{"国家": "BH","省": "Northern Governorate","城市": "Barbar"},
{"国家": "BH","省": "Northern Governorate","城市": "Bilad Al Qadeem"},
{"国家": "BH","省": "Northern Governorate","城市": "Bu Quwah"},
{"国家": "BH","省": "Northern Governorate","城市": "Budaiya"},
{"国家": "BH","省": "Northern Governorate","城市": "Buri"},
{"国家": "BH","省": "Muharraq Governorate","城市": "Busaiteen"},
{"国家": "BH","省": "Capital Governorate","城市": "Daih"},
{"国家": "BH","省": "Northern Governorate","城市": "Damistan"},
{"国家": "BH","省": "Northern Governorate","城市": "Dar Kulaib"},
{"国家": "BH","省": "Northern Governorate","城市": "Diraz"},
{"国家": "BH","省": "Muharraq Governorate","城市": "Galali"},
{"国家": "BH","省": "Northern Governorate","城市": "Hamala"},
{"国家": "BH","省": "Northern Governorate","城市": "Hillat Abdul Saleh"},
{"国家": "BH","省": "Central Governorate","城市": "Isa Town"},
{"国家": "BH","省": "Northern Governorate","城市": "Jannusan"},
{"国家": "BH","省": "Southern Governorate","城市": "Jaww"},
{"国家": "BH","省": "Northern Governorate","城市": "Jeblat Hebshi"},
{"国家": "BH","省": "Northern Governorate","城市": "Jid Al Haj"},
{"国家": "BH","省": "Central Governorate","城市": "Jid Ali"},
{"国家": "BH","省": "Northern Governorate","城市": "Jidda Island"},
{"国家": "BH","省": "Northern Governorate","城市": "Jiddah"},
{"国家": "BH","省": "Capital Governorate","城市": "Jidhafs"},
{"国家": "BH","省": "Central Governorate","城市": "Jurdab"},
{"国家": "BH","省": "Capital Governorate","城市": "Karbabad"},
{"国家": "BH","省": "Northern Governorate","城市": "Karranah"},
{"国家": "BH","省": "Northern Governorate","城市": "Karzakkan"},
{"国家": "BH","省": "Northern Governorate","城市": "Khamis"},
{"国家": "BH","省": "Northern Governorate","城市": "Madinat Hamad‎"},
{"国家": "BH","省": "Capital Governorate","城市": "Manama"},
{"国家": "BH","省": "Northern Governorate","城市": "Maqabah"},
{"国家": "BH","省": "Northern Governorate","城市": "North Sehla"},
{"国家": "BH","省": "Central Governorate","城市": "Nuwaidrat"},
{"国家": "BH","省": "Southern Governorate","城市": "Riffa"},
{"国家": "BH","省": "Northern Governorate","城市": "Saar"},















{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Adham"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Al Mada"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Aqiq"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Atawleh"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Badr Al Janoub"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Baha"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Biljurashi"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Gilwa"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Mandak"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Mikhwa"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Nimra"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Subheka"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Tanda"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Turaib"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "Wadi Bin Hasbal"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Abu Ajram"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Al Adari"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Al Laqayit"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "An Nabk Abu Qasr"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Ar Radifah"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "As Sulaimaniyah"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "At Tuwayr"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Domat Al Jandal"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Hadeethah"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Jouf"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Kara"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Qurayat"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Sakaka"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Tabrjal"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "Zallum"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Al Ais"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Al Mahd"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Bader"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Hinakeya"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Khaibar"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Madinah"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Mahad Al Dahab"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Medina"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Oula"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Yanbu"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Yanbu Al Baher"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "Yanbu Nakhil"},
{"国家": "SA","省": "Al-Qassim","城市": "Ad Dalfa'Ah"},
{"国家": "SA","省": "Al-Qassim","城市": "Al Ammarah"},
{"国家": "SA","省": "Al-Qassim","城市": "Al Asyah"},
{"国家": "SA","省": "Al-Qassim","城市": "Al Batra"},
{"国家": "SA","省": "Al-Qassim","城市": "Al Dalemya"},
{"国家": "SA","省": "Al-Qassim","城市": "Al Fuwaileq"},
{"国家": "SA","省": "Al-Qassim","城市": "Al Khishaybi"},
{"国家": "SA","省": "Al-Qassim","城市": "Al Midrij"},
{"国家": "SA","省": "Al-Qassim","城市": "Alnabhanya"},
{"国家": "SA","省": "Al-Qassim","城市": "Alrass"},
{"国家": "SA","省": "Al-Qassim","城市": "Ar Rishawiyah"},
{"国家": "SA","省": "Al-Qassim","城市": "Ayn Fuhayd"},
{"国家": "SA","省": "Al-Qassim","城市": "Badaya"},
{"国家": "SA","省": "Al-Qassim","城市": "Bukeiriah"},
{"国家": "SA","省": "Al-Qassim","城市": "Buraidah"},
{"国家": "SA","省": "Al-Qassim","城市": "Dariyah"},
{"国家": "SA","省": "Al-Qassim","城市": "Dulay Rashid"},
{"国家": "SA","省": "Al-Qassim","城市": "Kahlah"},
{"国家": "SA","省": "Al-Qassim","城市": "Kubadah"},
{"国家": "SA","省": "Al-Qassim","城市": "Midinhab"},
{"国家": "SA","省": "Al-Qassim","城市": "Muzneb"},
{"国家": "SA","省": "Al-Qassim","城市": "Onaiza"},
{"国家": "SA","省": "Al-Qassim","城市": "Oyoon Al Jawa"},
{"国家": "SA","省": "Al-Qassim","城市": "Qusayba"},
{"国家": "SA","省": "Al-Qassim","城市": "Riyadh Al Khabra"},
{"国家": "SA","省": "Al-Qassim","城市": "Sajir"},
{"国家": "SA","省": "Al-Qassim","城市": "Saqf"},
{"国家": "SA","省": "Al-Qassim","城市": "Uqlat Al Suqur"},
{"国家": "SA","省": "Al-Riyadh","城市": "Afif"},
{"国家": "SA","省": "Al-Riyadh","城市": "Aflaj"},
{"国家": "SA","省": "Al-Riyadh","城市": "Al Arja"},
{"国家": "SA","省": "Al-Riyadh","城市": "Al Qarin"},
{"国家": "SA","省": "Al-Riyadh","城市": "Alghat"},
{"国家": "SA","省": "Al-Riyadh","城市": "An Nafiah"},
{"国家": "SA","省": "Al-Riyadh","城市": "Artawiah"},
{"国家": "SA","省": "Al-Riyadh","城市": "As Sulayyil"},
{"国家": "SA","省": "Al-Riyadh","城市": "Ash Shaara"},
{"国家": "SA","省": "Al-Riyadh","城市": "Daelim"},
{"国家": "SA","省": "Al-Riyadh","城市": "Dawadmi"},
{"国家": "SA","省": "Al-Riyadh","城市": "Deraab"},
{"国家": "SA","省": "Al-Riyadh","城市": "Dere'Iyeh"},
{"国家": "SA","省": "Al-Riyadh","城市": "Dhurma"},
{"国家": "SA","省": "Al-Riyadh","城市": "Hareeq"},
{"国家": "SA","省": "Al-Riyadh","城市": "Hawtat Bani Tamim"},
{"国家": "SA","省": "Al-Riyadh","城市": "Hotat Sudair"},
{"国家": "SA","省": "Al-Riyadh","城市": "Huraymala"},
{"国家": "SA","省": "Al-Riyadh","城市": "Jalajel"},
{"国家": "SA","省": "Al-Riyadh","城市": "Khamaseen"},
{"国家": "SA","省": "Al-Riyadh","城市": "Kharj"},
{"国家": "SA","省": "Al-Riyadh","城市": "Layla"},
{"国家": "SA","省": "Al-Riyadh","城市": "Majma"},
{"国家": "SA","省": "Al-Riyadh","城市": "Mrat"},
{"国家": "SA","省": "Al-Riyadh","城市": "Muzahmiah"},
{"国家": "SA","省": "Al-Riyadh","城市": "Oyaynah"},
{"国家": "SA","省": "Al-Riyadh","城市": "Qasab"},
{"国家": "SA","省": "Al-Riyadh","城市": "Quwei'ieh"},
{"国家": "SA","省": "Al-Riyadh","城市": "Remah"},
{"国家": "SA","省": "Al-Riyadh","城市": "Riyadh"},
{"国家": "SA","省": "Al-Riyadh","城市": "Rowdat Sodair"},
{"国家": "SA","省": "Al-Riyadh","城市": "Rwaydah"},
{"国家": "SA","省": "Al-Riyadh","城市": "Sahna"},
{"国家": "SA","省": "Al-Riyadh","城市": "Sajir"},
{"国家": "SA","省": "Al-Riyadh","城市": "Salbookh"},
{"国家": "SA","省": "Al-Riyadh","城市": "Shaqra"},
{"国家": "SA","省": "Al-Riyadh","城市": "Shefa'A"},
{"国家": "SA","省": "Al-Riyadh","城市": "Tanumah"},
{"国家": "SA","省": "Al-Riyadh","城市": "Tebrak"},
{"国家": "SA","省": "Al-Riyadh","城市": "Thadek"},
{"国家": "SA","省": "Al-Riyadh","城市": "Tharmada"},
{"国家": "SA","省": "Al-Riyadh","城市": "Thumair"},
{"国家": "SA","省": "Al-Riyadh","城市": "Um Aljamajim"},
{"国家": "SA","省": "Al-Riyadh","城市": "Ushayqir"},
{"国家": "SA","省": "Al-Riyadh","城市": "Wadi El Dwaser"},
{"国家": "SA","省": "Al-Riyadh","城市": "Zulfi"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Afraa"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Bisha"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Abha"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Ahad Rufaidah"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Balahmar"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Balasmar"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Bareq"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Dhahran Al Janoob"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Harajah"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Kara'a"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Khamis Mushait"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Majarda"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Mohayel Aseer"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Namas"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Rejal Alma'A"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Sabt Alalayah"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Sarat Obeida"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Tanuma"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Tatleeth"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "Wadeien"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Batha"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Hafer Al Batin"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Hofuf"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Khafji"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Khobar"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Noweirieh"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Abqaiq"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Ain Dar"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Al Hassa"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Al-Jsh"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Anak"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Awamiah"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Baqiq"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Dammam"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Dhahran"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Harad"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Haweyah"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Jafar"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Jubail"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Khodaria"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Mubaraz"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Mulaija"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Nabiya"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Nisab"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Ojam"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Othmanyah"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Qarah"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Qariya Al Olaya"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Qatif"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Qaysoomah"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Rahima"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Ras Al Kheir"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Ras Tanura"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Rawdat Habbas"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Safanyah"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Safwa"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Salwa"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Sarar"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Satorp"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Seihat"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Tanjeeb"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Tarut"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Thuqba"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Udhaliyah"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "Uyun"},
{"国家": "SA","省": "Hail","城市": "Al Ajfar"},
{"国家": "SA","省": "Hail","城市": "Al hait"},
{"国家": "SA","省": "Hail","城市": "Al Wasayta"},
{"国家": "SA","省": "Hail","城市": "An Nuqrah"},
{"国家": "SA","省": "Hail","城市": "Ash Shamli"},
{"国家": "SA","省": "Hail","城市": "Ash Shananah"},
{"国家": "SA","省": "Hail","城市": "Baqa Ash Sharqiyah"},
{"国家": "SA","省": "Hail","城市": "Baqaa"},
{"国家": "SA","省": "Hail","城市": "Ghazalah"},
{"国家": "SA","省": "Hail","城市": "Hail"},
{"国家": "SA","省": "Hail","城市": "Mawqaq"},
{"国家": "SA","省": "Hail","城市": "Moqaq"},
{"国家": "SA","省": "Hail","城市": "Munifat Al Qaid"},
{"国家": "SA","省": "Hail","城市": "Qufar"},
{"国家": "SA","省": "Hail","城市": "Sadyan"},
{"国家": "SA","省": "Hail","城市": "Shinanh"},
{"国家": "SA","省": "Hail","城市": "Simira"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Abu Al Arj"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Abu Areish"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Ahad Masarha"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Al Ardah"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Al Idabi"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Bish"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Damad"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Darb"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Farasan"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Gizan"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Karboos"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Khasawyah"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Sabya"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Samtah"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "Thabya"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Alhada"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Amaq"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Asfan"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Ash Shara'I"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Ash Shuqaiq"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Bahara"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Bahrat Al Moujoud"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Birk"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Dhahban"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Hawea/Taif"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Ja'araneh"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Jeddah"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Jumum"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Khulais"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Khurma"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Laith"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Makkah"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Mastura"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Muthaleif"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Nimra"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Nwariah"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Qahmah"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Qunfudah"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Rabigh"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Rania"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Shoaiba"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Shraie'E"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Shumeisi"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Taiba"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Taif"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Thuwal"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Turba"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Wadi Fatmah"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "Zahban"},
{"国家": "SA","省": "Najran","城市": "Najran"},
{"国家": "SA","省": "Najran","城市": "Sharourah"},
{"国家": "SA","省": "Northern Borders {Al-Hudud ash-Shamaliyah}","城市": "Rafha"},
{"国家": "SA","省": "Northern Borders {Al-Hudud ash-Shamaliyah}","城市": "Arar"},
{"国家": "SA","省": "Northern Borders {Al-Hudud ash-Shamaliyah}","城市": "Hazm Al Jalamid"},
{"国家": "SA","省": "Northern Borders {Al-Hudud ash-Shamaliyah}","城市": "Turaif"},
{"国家": "SA","省": "Tabuk","城市": "Al Bada"},
{"国家": "SA","省": "Tabuk","城市": "Duba"},
{"国家": "SA","省": "Tabuk","城市": "Halat Ammar"},
{"国家": "SA","省": "Tabuk","城市": "Haqil"},
{"国家": "SA","省": "Tabuk","城市": "Tabuk"},
{"国家": "SA","省": "Tabuk","城市": "Tayma"},
{"国家": "SA","省": "Tabuk","城市": "Umluj"},
{"国家": "SA","省": "Tabuk","城市": "Wajeh (Al Wajh)"},

  









{"国家": "KW","省": "Hawally","城市": "Al-Bidea"},
{"国家": "KW","省": "Hawally","城市": "Al-Siddeeq"},
{"国家": "KW","省": "Hawally","城市": "Anjafa"},
{"国家": "KW","省": "Hawally","城市": "Bayan"},
{"国家": "KW","省": "Hawally","城市": "Hateen"},
{"国家": "KW","省": "Hawally","城市": "Hawally"},
{"国家": "KW","省": "Hawally","城市": "Jabriya"},
{"国家": "KW","省": "Hawally","城市": "Maidan Hawally"},
{"国家": "KW","省": "Hawally","城市": "Mishref"},
{"国家": "KW","省": "Hawally","城市": "Mubarak Al-Abdullah"},
{"国家": "KW","省": "Hawally","城市": "Rumaithiya"},
{"国家": "KW","省": "Hawally","城市": "Salam"},
{"国家": "KW","省": "Hawally","城市": "Salmiya"},
{"国家": "KW","省": "Hawally","城市": "Salwa"},
{"国家": "KW","省": "Hawally","城市": "Shaab"},
{"国家": "KW","省": "Hawally","城市": "Shuhada"},
{"国家": "KW","省": "Hawally","城市": "Zahra"},
{"国家": "KW","省": "Farwaniya","城市": "Abbasiya"},
{"国家": "KW","省": "Farwaniya","城市": "Abdullah Al Mubarak Al Sabah"},
{"国家": "KW","省": "Farwaniya","城市": "Abraq Khaitan"},
{"国家": "KW","省": "Farwaniya","城市": "Al-Dajeej"},
{"国家": "KW","省": "Farwaniya","城市": "Al-Shadadiya"},
{"国家": "KW","省": "Farwaniya","城市": "Andalous"},
{"国家": "KW","省": "Farwaniya","城市": "Ardiya"},
{"国家": "KW","省": "Farwaniya","城市": "Ardiya Small Industrial"},
{"国家": "KW","省": "Farwaniya","城市": "Ardiya Storage Zone"},
{"国家": "KW","省": "Farwaniya","城市": "Doha"},
{"国家": "KW","省": "Farwaniya","城市": "Farwaniyah"},
{"国家": "KW","省": "Farwaniya","城市": "Firdous"},
{"国家": "KW","省": "Farwaniya","城市": "Ishbiliya"},
{"国家": "KW","省": "Farwaniya","城市": "Jeleeb Al-Shuyoukh"},
{"国家": "KW","省": "Farwaniya","城市": "Khaitan"},
{"国家": "KW","省": "Farwaniya","城市": "Kuwait International Airport"},
{"国家": "KW","省": "Farwaniya","城市": "Omariya"},
{"国家": "KW","省": "Farwaniya","城市": "Rabia"},
{"国家": "KW","省": "Farwaniya","城市": "Rai"},
{"国家": "KW","省": "Farwaniya","城市": "Rehab"},
{"国家": "KW","省": "Farwaniya","城市": "Rigai"},
{"国家": "KW","省": "Farwaniya","城市": "Sabah Al Nasser"},
{"国家": "KW","省": "Farwaniya","城市": "Sheikh Saad Aviation Terminal"},
{"国家": "KW","省": "Farwaniya","城市": "South Khaitan-Exhibits"},
{"国家": "KW","省": "Ahmadi","城市": "Abu Halifa"},
{"国家": "KW","省": "Ahmadi","城市": "Ahmadi"},
{"国家": "KW","省": "Ahmadi","城市": "Al Khiran"},
{"国家": "KW","省": "Ahmadi","城市": "Al Wafrah"},
{"国家": "KW","省": "Ahmadi","城市": "Al-Julaia'a"},
{"国家": "KW","省": "Ahmadi","城市": "Al-Nuwaiseeb"},
{"国家": "KW","省": "Ahmadi","城市": "Al-Riqqa"},
{"国家": "KW","省": "Ahmadi","城市": "Ali Sabah Al Salem"},
{"国家": "KW","省": "Ahmadi","城市": "Assabahiyah"},
{"国家": "KW","省": "Ahmadi","城市": "Bnaider"},
{"国家": "KW","省": "Ahmadi","城市": "Dahar"},
{"国家": "KW","省": "Ahmadi","城市": "Eqaila"},
{"国家": "KW","省": "Ahmadi","城市": "Fahad Al Ahmad"},
{"国家": "KW","省": "Ahmadi","城市": "Fahaheel"},
{"国家": "KW","省": "Ahmadi","城市": "Fintas"},
{"国家": "KW","省": "Ahmadi","城市": "Hadiya"},
{"国家": "KW","省": "Ahmadi","城市": "Jaber Al Ali"},
{"国家": "KW","省": "Ahmadi","城市": "Mahboula"},
{"国家": "KW","省": "Ahmadi","城市": "Mangaf"},
{"国家": "KW","省": "Ahmadi","城市": "Sabah Al Ahmad"},
{"国家": "KW","省": "Ahmadi","城市": "Shalayhat Al Dubaiya"},
{"国家": "KW","省": "Ahmadi","城市": "Shalayhat Mina Abdullah"},
{"国家": "KW","省": "Ahmadi","城市": "Shuaiba Block 1"},
{"国家": "KW","省": "Ahmadi","城市": "West Industrial Shuaiba"},
{"国家": "KW","省": "Ahmadi","城市": "Zour"},
{"国家": "KW","省": "Kuwait City","城市": "Abdullah al-Salem"},
{"国家": "KW","省": "Kuwait City","城市": "Adailiya"},
{"国家": "KW","省": "Kuwait City","城市": "Bneid Al Qar"},
{"国家": "KW","省": "Kuwait City","城市": "Daiya"},
{"国家": "KW","省": "Kuwait City","城市": "Dasma"},
{"国家": "KW","省": "Kuwait City","城市": "Dasman"},
{"国家": "KW","省": "Kuwait City","城市": "Faiha"},
{"国家": "KW","省": "Kuwait City","城市": "Granada"},
{"国家": "KW","省": "Kuwait City","城市": "Jaber Al Ahmad"},
{"国家": "KW","省": "Kuwait City","城市": "Jibla"},
{"国家": "KW","省": "Kuwait City","城市": "Kaifan"},
{"国家": "KW","省": "Kuwait City","城市": "Khaldiya"},
{"国家": "KW","省": "Kuwait City","城市": "Kuwait City"},
{"国家": "KW","省": "Kuwait City","城市": "Kuwait Free Trade Zone"},
{"国家": "KW","省": "Kuwait City","城市": "Mansouriya"},
{"国家": "KW","省": "Kuwait City","城市": "Mirqab"},
{"国家": "KW","省": "Kuwait City","城市": "Nahdha"},
{"国家": "KW","省": "Kuwait City","城市": "North West Al-Sulaibikhat"},
{"国家": "KW","省": "Kuwait City","城市": "Nuzha"},
{"国家": "KW","省": "Kuwait City","城市": "Qadsiya"},
{"国家": "KW","省": "Kuwait City","城市": "Qairawan"},
{"国家": "KW","省": "Kuwait City","城市": "Qortuba"},
{"国家": "KW","省": "Kuwait City","城市": "Rawda"},
{"国家": "KW","省": "Kuwait City","城市": "Salhiya"},
{"国家": "KW","省": "Kuwait City","城市": "Shamiya"},
{"国家": "KW","省": "Kuwait City","城市": "Sharq"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Administrative"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Industrial"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Industrial 1"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Industrial 2"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Industrial 3"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Residential"},
{"国家": "KW","省": "Kuwait City","城市": "Souk Al Mubarakeya"},
{"国家": "KW","省": "Kuwait City","城市": "Sulaibikhat"},
{"国家": "KW","省": "Kuwait City","城市": "Surra"},
{"国家": "KW","省": "Kuwait City","城市": "Yarmouk"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Abu Al Hasaniya"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Abu Fatira"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Adan"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Al-Masayel"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Fnaitees"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Messila"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Mubarak Al Kabeer"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Qurain"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Qusor"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Sabah Al Salem"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Sabhan Industrial Area"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "South Wista"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "West of Abu Fatira Al-Herafia"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Wista"},
{"国家": "KW","省": "Jahra","城市": "Al Sulaibiya Industrial 1"},
{"国家": "KW","省": "Jahra","城市": "Al Sulaibiya Industrial 2"},
{"国家": "KW","省": "Jahra","城市": "Amgarah Industrial Area"},
{"国家": "KW","省": "Jahra","城市": "Jahra"},
{"国家": "KW","省": "Jahra","城市": "Naeem"},
{"国家": "KW","省": "Jahra","城市": "Naseem"},
{"国家": "KW","省": "Jahra","城市": "Oyoun"},
{"国家": "KW","省": "Jahra","城市": "Qasr"},
{"国家": "KW","省": "Jahra","城市": "Saad Al Abdullah"},
{"国家": "KW","省": "Jahra","城市": "Sulaibiya"},
{"国家": "KW","省": "Jahra","城市": "Taima'"},
{"国家": "KW","省": "Jahra","城市": "Waha"},







{"国家": "OM","省": "Oman","城市": "Ruwi"},
{"国家": "OM","省": "Oman","城市": "Amerat"},
{"国家": "OM","省": "Oman","城市": "Wadi Kabir"},
{"国家": "OM","省": "Oman","城市": "Mawaleh"},
{"国家": "OM","省": "Oman","城市": "Ghala"},
{"国家": "OM","省": "Oman","城市": "Hamriya"},
{"国家": "OM","省": "Oman","城市": "Sidab"},
{"国家": "OM","省": "Oman","城市": "Al Khodh"},
{"国家": "OM","省": "Oman","城市": "Rusayl"},
{"国家": "OM","省": "Oman","城市": "Madinat Sultan Qaboos"},
{"国家": "OM","省": "Oman","城市": "Bowsher"},
{"国家": "OM","省": "Oman","城市": "Muscat"},
{"国家": "OM","省": "Oman","城市": "Azaiba"},
{"国家": "OM","省": "Oman","城市": "Al Awabi - Muscat"},
{"国家": "OM","省": "Oman","城市": "Al Khuwair"},
{"国家": "OM","省": "Oman","城市": "Qurum"},
{"国家": "OM","省": "Oman","城市": "Muttrah"},
{"国家": "OM","省": "Oman","城市": "Seeb"},
{"国家": "OM","省": "Oman","城市": "Ghubra"},
{"国家": "OM","省": "Oman","城市": "Wadi Adai"},
{"国家": "OM","省": "Oman","城市": "Jibroo"},
{"国家": "OM","省": "Oman","城市": "Wattaya"},
{"国家": "OM","省": "Oman","城市": "Al Awabi - Barka"},
{"国家": "OM","省": "Oman","城市": "Al Duqm"},
{"国家": "OM","省": "Oman","城市": "Al Hamra"},
{"国家": "OM","省": "Oman","城市": "Al Ghazir"},
{"国家": "OM","省": "Oman","城市": "Al Kabil"},
{"国家": "OM","省": "Oman","城市": "Al Kamil Wal Wafi"},
{"国家": "OM","省": "Oman","城市": "Al Mudhaibi"},
{"国家": "OM","省": "Oman","城市": "Sunaina"},
{"国家": "OM","省": "Oman","城市": "Yankul"},
{"国家": "OM","省": "Oman","城市": "Bahla"},
{"国家": "OM","省": "Oman","城市": "Barka"},
{"国家": "OM","省": "Oman","城市": "Bidbid"},
{"国家": "OM","省": "Oman","城市": "Al Bidayah"},
{"国家": "OM","省": "Oman","城市": "Bidiya"},
{"国家": "OM","省": "Oman","城市": "BURAIMI"},
{"国家": "OM","省": "Oman","城市": "Dhank"},
{"国家": "OM","省": "Oman","城市": "Diba"},
{"国家": "OM","省": "Oman","城市": "Falaj Al Qabail"},
{"国家": "OM","省": "Oman","城市": "Sohar"},
{"国家": "OM","省": "Oman","城市": "Fanja"},
{"国家": "OM","省": "Oman","城市": "Ibra"},
{"国家": "OM","省": "Oman","城市": "Ibri"},
{"国家": "OM","省": "Oman","城市": "Izki"},
{"国家": "OM","省": "Oman","城市": "Jaalan Bani Bu Ali"},
{"国家": "OM","省": "Oman","城市": "Jaalan ni Bu Hassan"},
{"国家": "OM","省": "Oman","城市": "Khabourah"},
{"国家": "OM","省": "Oman","城市": "Liwa"},
{"国家": "OM","省": "Oman","城市": "Madha"},
{"国家": "OM","省": "Oman","城市": "Manah"},
{"国家": "OM","省": "Oman","城市": "Masirah"},
{"国家": "OM","省": "Oman","城市": "Musannah"},
{"国家": "OM","省": "Oman","城市": "Nakhl"},
{"国家": "OM","省": "Oman","城市": "Nizwa"},
{"国家": "OM","省": "Oman","城市": "Qurayat"},
{"国家": "OM","省": "Oman","城市": "rustaq"},
{"国家": "OM","省": "Oman","城市": "Saham"},
{"国家": "OM","省": "Oman","城市": "Salalah"},
{"国家": "OM","省": "Oman","城市": "Samayil"},
{"国家": "OM","省": "Oman","城市": "Shinas"},
{"国家": "OM","省": "Oman","城市": "Sur"},
{"国家": "OM","省": "Oman","城市": "Suwaiq"},









  ]