var zhongdong6guo = [
  {
    国家: "JO",
    省: "Jerash Governorate",
    城市: "Jarash",
    区: "Jarash Qasabah District",
  },
  {
    国家: "JO",
    省: "Jerash Governorate",
    城市: "Jarash",
    区: "Mestabah Sub-District",
  },
  {
    国家: "JO",
    省: "Jerash Governorate",
    城市: "Jarash",
    区: "Borma Sub-District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Ma'an Qasabah District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Mraighah Sub-District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Petra District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Shobak Qasabah District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Udhruh Sub-District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Huseiniya District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Iell Sub-District",
  },
  {
    国家: "JO",
    省: "Maan Governorate",
    城市: "Maan",
    区: "Jafr Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Faisaliah Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Jrainah Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Madaba Qasabah District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Maeen Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Mlaih Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Areedh Sub-District",
  },
  {
    国家: "JO",
    省: "Madaba Governorate",
    城市: "Madaba",
    区: "Dieban District",
  },
  {
    国家: "JO",
    省: "Ajloun Governorate",
    城市: "Ajlun",
    区: "Ajlun Qasabah District",
  },
  {
    国家: "JO",
    省: "Ajloun Governorate",
    城市: "Ajlun",
    区: "Kufranjah District",
  },
  {
    国家: "JO",
    省: "Ajloun Governorate",
    城市: "Ajlun",
    区: "Orjan SubDistrict",
  },
  {
    国家: "JO",
    省: "Ajloun Governorate",
    城市: "Ajlun",
    区: "Sakhrah Sub-District",
  },
  {
    国家: "JO",
    省: "Aqaba Governorate",
    城市: "Al-Aqabah",
    区: "Wadi Araba Sub-District",
  },
  {
    国家: "JO",
    省: "Aqaba Governorate",
    城市: "Al-Aqabah",
    区: "Aqaba Qasabah District",
  },
  {
    国家: "JO",
    省: "Aqaba Governorate",
    城市: "Al-Aqabah",
    区: "Diesah Sub-District",
  },
  {
    国家: "JO",
    省: "Aqaba Governorate",
    城市: "Al-Aqabah",
    区: "Quairah District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Shoonah Janoobiah District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Zayy Sub-District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Ain Albasha District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Al Ardha Sub-District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Dair Alla District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Ira & Yargha Sub-District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Mahes & Fuhais District",
  },
  {
    国家: "JO",
    省: "Balqa Governorate",
    城市: "As-Salt",
    区: "Salt Qasabah District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Mazar Janoobee District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Mo'aab Sub-District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Mowjeb Sub-District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Qasr District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Qatraneh District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Aghwar Janoobiyah District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Ayy District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Faqo'e District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Ghawr Almazra'a Sub-District",
  },
  {
    国家: "JO",
    省: "Karak Governorate",
    城市: "Al-Karak",
    区: "Karak Qasabah District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Sama Serhan District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Um Al-Jemal Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Um-Elqotain Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Hosha Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Khaldiyah Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Mafraq Qasabah District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Manshiyah Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "North West Badiah District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Rihab Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Rwaished District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Sabha Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Al-Badiah Ash-Shamaliyah District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Bal'ama Sub-District",
  },
  {
    国家: "JO",
    省: "Mafraq Governorate",
    城市: "Al-Mafraq",
    区: "Dair Al Kahaf Sub-District",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Sweileh"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Tareq"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Tla al-Ali",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Wadi As-Seir",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Zahran"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Marj Al Hamam",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Marka"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Na'ur"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Ohud"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Ras al-Ain",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Sahab"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Shafa Badran",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Yarmouk",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al-Muwaqqar",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Badr"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Badr AjJadidah",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Basman"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Husban & Um al Basateen",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Kherbat as-Souk",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Khilda"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Abu Nseir"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Abdali"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Jizah"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Jubeiha",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Madinah",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Muqabalein",
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Naser"
  },
  {
    国家: "JO",
    省: "Amman Governorate",
    城市: "Amman",
    区: "Al Qweismeh",
  },
  {
    国家: "JO",
    省: "Tafilah Governorate",
    城市: "At-Tafilah",
    区: "Bsaira District",
  },
  {
    国家: "JO",
    省: "Tafilah Governorate",
    城市: "At-Tafilah",
    区: "Hasa District",
  },
  {
    国家: "JO",
    省: "Tafilah Governorate",
    城市: "At-Tafilah",
    区: "Tafiela Qasabah District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Azraq Sub-District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Bierain Sub-District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Dhlail Sub-District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Hashemiyah District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Russeifa District",
  },
  {
    国家: "JO",
    省: "Zarqa Governorate",
    城市: "Az-Zarqa",
    区: "Zarqa Qasabah District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Bani Kinanah Department",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Bani Obeid District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Bayt Ras"
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Irbid Qasabah District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Ramtha District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Taybeh District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Wastiyyah District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Aghwar Shamaliyah District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Al Mazar al Shamali",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Al-Kourah District",
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "At-Turrah"
  },
  {
    国家: "JO",
    省: "Irbid Governorate",
    城市: "Irbid",
    区: "Aydun"
  },











  


  {"国家": "AE","省": "Abu Dhabi","城市": "الدووى"},
  {"国家": "AE","省": "Abu Dhabi","城市": "حبشان"},
  {"国家": "AE","省": "Abu Dhabi","城市": "العاردية"},
  {"国家": "AE","省": "Abu Dhabi","城市": "سيلا"},
  {"国家": "AE","省": "Abu Dhabi","城市": "الدراويية"},
  {"国家": "AE","省": "Abu Dhabi","城市": "سوياتهان"},
  {"国家": "AE","省": "Abu Dhabi","城市": "الدهيد"},
  {"国家": "AE","省": "Abu Dhabi","城市": "الدس."},
  {"国家": "AE","省": "Abu Dhabi","城市": "المفرق"},
  {"国家": "AE","省": "Abu Dhabi","城市": "الختيم"},
  {"国家": "AE","省": "Abu Dhabi","城市": "المرفأ"},
  {"国家": "AE","省": "Dubai","城市": "مدينة دبي للإنترنت"},
  {"国家": "AE","省": "Dubai","城市": "بر دبي"},
  {"国家": "AE","省": "Dubai","城市": "مينا سوفوه"},
  {"国家": "AE","省": "Sharjah","城市": "حمارة"},
  {"国家": "AE","省": "Dubai","城市": "الكرامة"},
  {"国家": "AE","省": "Dubai","城市": "شنداغه"},
  {"国家": "AE","省": "Dubai","城市": "القوز"},
  {"国家": "AE","省": "Dubai","城市": "ديرة"},
  {"国家": "AE","省": "Sharjah","城市": "الخشفة"},
  {"国家": "AE","省": "Dubai","城市": "مجتمع ريم"},
  {"国家": "AE","省": "Dubai","城市": "دبي"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "الجزيرة"},
  {"国家": "AE","省": "Sharjah","城市": "الرملة"},
  {"国家": "AE","省": "Sharjah","城市": "صبا"},
  {"国家": "AE","省": "Dubai","城市": "جبل علي"},
  {"国家": "AE","省": "Um Al Quiwan","城市": "ام القيووان"},
  {"国家": "AE","省": "Fujairah","城市": "قيدفا"},
  {"国家": "AE","省": "Sharjah","城市": "أكانت"},
  {"国家": "AE","省": "Dubai","城市": "الرواعية"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "خور خوير"},
  {"国家": "AE","省": "Dubai","城市": "غانثوت"},
  {"国家": "AE","省": "Fujairah","城市": "كيدفا"},
  {"国家": "AE","省": "Dubai","城市": "حتا"},
  {"国家": "AE","省": "Fujairah","城市": "الحايل"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "الشما"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "خات"},
  {"国家": "AE","省": "Al Ain","城市": "ريما"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "عائم"},
  {"国家": "AE","省": "Al Ain","城市": "الحيدر"},
  {"国家": "AE","省": "Fujairah","城市": "فورفار"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "الحمرانية"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "الشام"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "الولية"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "المنامة"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "adhan."},
  {"国家": "AE","省": "Abu Dhabi","城市": "بلبين"},
  {"国家": "AE","省": "Abu Dhabi","城市": "المقدمة"},
  {"国家": "AE","省": "Abu Dhabi","城市": "مصفح"},
  {"国家": "AE","省": "Abu Dhabi","城市": "أبوظبي"},
  {"国家": "AE","省": "Abu Dhabi","城市": "أم النار"},
  {"国家": "AE","省": "Ajman","城市": "مدينة عجمان"},
  {"国家": "AE","省": "Ajman","城市": "ماسفوت"},
  {"国家": "AE","省": "Sharjah","城市": "الرافاعة"},
  {"国家": "AE","省": "Sharjah","城市": "نخيلات"},
  {"国家": "AE","省": "Ajman","城市": "مشرف"},
  {"国家": "AE","省": "Fujairah","城市": "غرفة"},
  {"国家": "AE","省": "Fujairah","城市": "دبا البيارة"},
  {"国家": "AE","省": "Fujairah","城市": "خور كلباء"},
  {"国家": "AE","省": "Ras Al Khaimah","城市": "الجزيرة الحمرا"},
  {"国家": "AE","省": "Sharjah","城市": "بوتين"},
  {"国家": "AE","省": "Sharjah","城市": "الرموقة"},
  {"国家": "AE","省": "Sharjah","城市": "خرايان"},
  

  










{"国家": "QA","省": "Doha","城市": "الجسرة"},
{"国家": "QA","省": "Doha","城市": "البدا"},
{"国家": "QA","省": "Doha","城市": "فريج محمد بن جاسم"},
{"国家": "QA","省": "Doha","城市": "مشاكر"},
{"国家": "QA","省": "Doha","城市": "النجادة"},
{"国家": "QA","省": "Doha","城市": "برها الجفيري"},
{"国家": "QA","省": "Doha","城市": "فريج الاسماك"},
{"国家": "QA","省": "Doha","城市": "القديم الغانم"},
{"国家": "QA","省": "Doha","城市": "السوق"},
{"国家": "QA","省": "Doha","城市": "وادي السيل"},
{"国家": "QA","省": "Doha","城市": "حملة"},
{"国家": "QA","省": "Doha","城市": "فريج عبد العزيز"},
{"国家": "QA","省": "Doha","城市": "الدوحة الجديدة"},
{"国家": "QA","省": "Doha","城市": "الرفااع"},
{"国家": "QA","省": "Doha","城市": "القديم هيتمي"},
{"国家": "QA","省": "Doha","城市": "كما صلاح"},
{"国家": "QA","省": "Doha","城市": "المرقاب"},
{"国家": "QA","省": "Doha","城市": "ميناء الدوحة"},
{"国家": "QA","省": "Doha","城市": "فريج بن محمود"},
{"国家": "QA","省": "Doha","城市": "روضة الخيل"},
{"国家": "QA","省": "Doha","城市": "فريج بن دورهام"},
{"国家": "QA","省": "Doha","城市": "المنصورة"},
{"国家": "QA","省": "Doha","城市": "نجمة"},
{"国家": "QA","省": "Doha","城市": "أم الغويله"},
{"国家": "QA","省": "Doha","城市": "الخلفات"},
{"国家": "QA","省": "Doha","城市": "راس أبو عبود"},
{"国家": "QA","省": "Doha","城市": "Duheail."},
{"国家": "QA","省": "Doha","城市": "أم اليهبة"},
{"国家": "QA","省": "Doha","城市": "مدينة خليفة الشمال"},
{"国家": "QA","省": "Doha","城市": "دال الحمام"},
{"国家": "QA","省": "Doha","城市": "المريحة"},
{"国家": "QA","省": "Doha","城市": "مدينة خليفة الجنوبية"},
{"国家": "QA","省": "Doha","城市": "فريج كليب"},
{"国家": "QA","省": "Doha","城市": "المسيلة"},
{"国家": "QA","省": "Doha","城市": "فريج بن عمران"},
{"国家": "QA","省": "Doha","城市": "آل هيتمي الجديد"},
{"国家": "QA","省": "Doha","城市": "مدينة حمد الطبية"},
{"国家": "QA","省": "Doha","城市": "السد"},
{"国家": "QA","省": "Doha","城市": "الجديد المرقاب"},
{"国家": "QA","省": "Doha","城市": "فريج النصر"},
{"国家": "QA","省": "Doha","城市": "سلاتة جديدة"},
{"国家": "QA","省": "Doha","城市": "nuaija."},
{"国家": "QA","省": "Doha","城市": "الهلال"},
{"国家": "QA","省": "Doha","城市": "المطار القديم"},
{"国家": "QA","省": "Doha","城市": "الثمامة"},
{"国家": "QA","省": "Doha","城市": "مطار الدوحة الدولي"},
{"国家": "QA","省": "Doha","城市": "منطقة صناعية"},
{"国家": "QA","省": "Doha","城市": "الدفنا"},
{"国家": "QA","省": "Doha","城市": "القصر"},
{"国家": "QA","省": "Doha","城市": "أونايزا"},
{"国家": "QA","省": "Doha","城市": "لجميلات"},
{"国家": "QA","省": "Doha","城市": "الطقافية"},
{"国家": "QA","省": "Doha","城市": "حازم المرخية"},
{"国家": "QA","省": "Doha","城市": "jelaiah."},
{"国家": "QA","省": "Doha","城市": "الترفه"},
{"国家": "QA","省": "Doha","城市": "جيريان نجيماء"},
{"国家": "QA","省": "Al Rayyan","城市": "الغرافة"},
{"国家": "QA","省": "Al Rayyan","城市": "غرافة الريان"},
{"国家": "QA","省": "Al Rayyan","城市": "إيزغاوا"},
{"国家": "QA","省": "Al Rayyan","城市": "بني هاجر"},
{"国家": "QA","省": "Al Rayyan","城市": "الساج"},
{"国家": "QA","省": "Al Rayyan","城市": "روضة egdaim."},
{"国家": "QA","省": "Al Rayyan","城市": "العيئة"},
{"国家": "QA","省": "Al Rayyan","城市": "اللقطة"},
{"国家": "QA","省": "Al Rayyan","城市": "Lebday."},
{"国家": "QA","省": "Al Rayyan","城市": "القديم الريان"},
{"国家": "QA","省": "Al Rayyan","城市": "الشيغ"},
{"国家": "QA","省": "Al Rayyan","城市": "فريج الزعيم"},
{"国家": "QA","省": "Al Rayyan","城市": "الريان الجديدة"},
{"国家": "QA","省": "Al Rayyan","城市": "الوجبة"},
{"国家": "QA","省": "Al Rayyan","城市": "معيذر"},
{"国家": "QA","省": "Al Rayyan","城市": "فريج الامير"},
{"国家": "QA","省": "Al Rayyan","城市": "luaib."},
{"国家": "QA","省": "Al Rayyan","城市": "موريخ"},
{"国家": "QA","省": "Al Rayyan","城市": "باياء"},
{"国家": "QA","省": "Al Rayyan","城市": "ميهيرجا"},
{"国家": "QA","省": "Al Rayyan","城市": "فريج السودان"},
{"国家": "QA","省": "Al Rayyan","城市": "الوعب"},
{"国家": "QA","省": "Al Rayyan","城市": "العزيزية"},
{"国家": "QA","省": "Al Rayyan","城市": "فريج الغانم الجديد"},
{"国家": "QA","省": "Al Rayyan","城市": "فريج المورا"},
{"国家": "QA","省": "Al Rayyan","城市": "فريج المناصير"},
{"国家": "QA","省": "Al Rayyan","城市": "بو sidra."},
{"国家": "QA","省": "Al Rayyan","城市": "الشريعة"},
{"国家": "QA","省": "Al Rayyan","城市": "المعمراد"},
{"国家": "QA","省": "Al Rayyan","城市": "فريج العسيري"},
{"国家": "QA","省": "Al Rayyan","城市": "فريج الخطيف"},
{"国家": "QA","省": "Al Rayyan","城市": "بو سمرا"},
{"国家": "QA","省": "Al Rayyan","城市": "المعمورة"},
{"国家": "QA","省": "Al Rayyan","城市": "أبو هامور"},
{"国家": "QA","省": "Al Rayyan","城市": "mesaimeer."},
{"国家": "QA","省": "Al Rayyan","城市": "عين خالد"},
{"国家": "QA","省": "Al Rayyan","城市": "mebaireek."},
{"国家": "QA","省": "Al Rayyan","城市": "القرانة"},
{"国家": "QA","省": "Al Rayyan","城市": "ابو سمرا"},
{"国家": "QA","省": "Al Rayyan","城市": "صعدا نظيل"},
{"国家": "QA","省": "Al Daayen","城市": "جبل ثايليب"},
{"国家": "QA","省": "Al Daayen","城市": "الخرايج"},
{"国家": "QA","省": "Al Daayen","城市": "لوسيل"},
{"国家": "QA","省": "Al Daayen","城市": "الزله"},
{"国家": "QA","省": "Al Daayen","城市": "وادي البنات"},
{"国家": "QA","省": "Al Daayen","城市": "لفة"},
{"国家": "QA","省": "Al Daayen","城市": "البيب"},
{"国家": "QA","省": "Al Daayen","城市": "Jeryan Jenaihat."},
{"国家": "QA","省": "Al Daayen","城市": "الخيصة"},
{"国家": "QA","省": "Al Daayen","城市": "روضة الحمامة"},
{"国家": "QA","省": "Al Daayen","城市": "وادي الواصت"},
{"国家": "QA","省": "Al Daayen","城市": "السخامة"},






{"国家": "BH","省": "Central Governorate","城市": "عالي"},
{"国家": "BH","省": "Central Governorate","城市": "هورة عالي"},
{"国家": "BH","省": "Central Governorate","城市": "معامير"},
{"国家": "BH","省": "Muharraq Governorate","城市": "المحرق"},
{"国家": "BH","省": "Northern Governorate","城市": "أَبُو بَهَام"},
{"国家": "BH","省": "Northern Governorate","城市": "أبو صيبع"},
{"国家": "BH","省": "Capital Governorate","城市": "البرهامة"},
{"国家": "BH","省": "Muharraq Governorate","城市": "الدير"},
{"国家": "BH","省": "Southern Governorate","城市": "الدور"},
{"国家": "BH","省": "Central Governorate","城市": "العكر"},
{"国家": "BH","省": "Northern Governorate","城市": "الحجر"},
{"国家": "BH","省": "Muharraq Governorate","城市": "الحد"},
{"国家": "BH","省": "Northern Governorate","城市": "الجنبية"},
{"国家": "BH","省": "Northern Governorate","城市": "الجسرة"},
{"国家": "BH","省": "Northern Governorate","城市": "اللوزي"},
{"国家": "BH","省": "Northern Governorate","城市": "المالكية"},
{"国家": "BH","省": "Northern Governorate","城市": "المقشع"},
{"国家": "BH","省": "Northern Governorate","城市": "المرخ"},
{"国家": "BH","省": "Southern Governorate","城市": "المزروعية"},
{"国家": "BH","省": "Northern Governorate","城市": "المصلى"},
{"国家": "BH","省": "Northern Governorate","城市": "القدم"},
{"国家": "BH","省": "Capital Governorate","城市": "القلعة"},
{"国家": "BH","省": "Northern Governorate","城市": "القرية"},
{"国家": "BH","省": "Northern Governorate","城市": "الصافرية"},
{"国家": "BH","省": "Muharraq Governorate","城市": "الساية"},
{"国家": "BH","省": "Muharraq Governorate","城市": "عراد"},
{"国家": "BH","省": "Southern Governorate","城市": "عسكر"},
{"国家": "BH","省": "Southern Governorate","城市": "عوالي"},
{"国家": "BH","省": "Northern Governorate","城市": "بني جمرة"},
{"国家": "BH","省": "Northern Governorate","城市": "باربار"},
{"国家": "BH","省": "Northern Governorate","城市": "البلاد القديم"},
{"国家": "BH","省": "Northern Governorate","城市": "بو قوة"},
{"国家": "BH","省": "Northern Governorate","城市": "البديع"},
{"国家": "BH","省": "Northern Governorate","城市": "بوري"},
{"国家": "BH","省": "Muharraq Governorate","城市": "البسيتين"},
{"国家": "BH","省": "Capital Governorate","城市": "الديه"},
{"国家": "BH","省": "Northern Governorate","城市": "دمستان"},
{"国家": "BH","省": "Northern Governorate","城市": "دار كليب"},
{"国家": "BH","省": "Northern Governorate","城市": "الدراز"},
{"国家": "BH","省": "Muharraq Governorate","城市": "قلالي"},
{"国家": "BH","省": "Northern Governorate","城市": "الهملة"},
{"国家": "BH","省": "Northern Governorate","城市": "حلة عبد الصالح"},
{"国家": "BH","省": "Central Governorate","城市": "مدينة عيسى"},
{"国家": "BH","省": "Northern Governorate","城市": "جنوسان"},
{"国家": "BH","省": "Southern Governorate","城市": "جو"},
{"国家": "BH","省": "Northern Governorate","城市": "جبلة حبشي"},
{"国家": "BH","省": "Northern Governorate","城市": "جد الحاج"},
{"国家": "BH","省": "Central Governorate","城市": "جد علي"},
{"国家": "BH","省": "Northern Governorate","城市": "المدينة الشمالية"},
{"国家": "BH","省": "Northern Governorate","城市": "جدة"},
{"国家": "BH","省": "Capital Governorate","城市": "جدحفص"},
{"国家": "BH","省": "Central Governorate","城市": "جرداب"},
{"国家": "BH","省": "Capital Governorate","城市": "كرباباد"},
{"国家": "BH","省": "Northern Governorate","城市": "كرانة"},
{"国家": "BH","省": "Northern Governorate","城市": "كرزكان"},
{"国家": "BH","省": "Northern Governorate","城市": "الخميس"},
{"国家": "BH","省": "Northern Governorate","城市": "مدينة حمد"},
{"国家": "BH","省": "Capital Governorate","城市": "المنامة"},
{"国家": "BH","省": "Northern Governorate","城市": "مقابة"},
{"国家": "BH","省": "Northern Governorate","城市": "شمال السهلة"},
{"国家": "BH","省": "Central Governorate","城市": "النويدرات"},
{"国家": "BH","省": "Southern Governorate","城市": "الرفاع"},
{"国家": "BH","省": "Northern Governorate","城市": "سار"},
















{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "أضم"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "المضة "},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "العقيق"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "الأطاوله"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "بدر الجنوب"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "الباحة"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "بلجرشي"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "القلوة"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "المندق"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "المخواة"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "نمرة"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "الصبيخة"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "تندحة"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "طريب"},
{"国家": "SA","省": "Al-Baha{Al-Bahah}","城市": "وادي ابن هشبل"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "أبو عجرم"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "الأضارع"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": " اللقايط"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "النبك أبو قصر"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "الرديفة"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "السليمانية"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "الطوير"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "دومة الجندل"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "الحديثه"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "الجوف"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "الجوف"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "القريات"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "سكاكا"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "طبرجل"},
{"国家": "SA","省": "Al-Jouf{Al Jawf}","城市": "زلوم"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "العيص"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "المَـهـد"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "بدر"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "الحناكية"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "خيبر"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "المدينة المنورة"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "مهد الذهب"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "المدينة المنورة"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "العلا"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "ينبع"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "ينبع البحر"},
{"国家": "SA","省": "Al-Madinah Al-Monawarah","城市": "ينبع النخل"},
{"国家": "SA","省": "Al-Qassim","城市": "القصيم"},
{"国家": "SA","省": "Al-Qassim","城市": "العمار"},
{"国家": "SA","省": "Al-Qassim","城市": "الأسياح"},
{"国家": "SA","省": "Al-Qassim","城市": "البتراء"},
{"国家": "SA","省": "Al-Qassim","城市": "الدليمية"},
{"国家": "SA","省": "Al-Qassim","城市": "الفويلق"},
{"国家": "SA","省": "Al-Qassim","城市": "الخشيبي"},
{"国家": "SA","省": "Al-Qassim","城市": "المدرج"},
{"国家": "SA","省": "Al-Qassim","城市": "النبهانية"},
{"国家": "SA","省": "Al-Qassim","城市": "الرس"},
{"国家": "SA","省": "Al-Qassim","城市": "الرشاوية"},
{"国家": "SA","省": "Al-Qassim","城市": "عين ابن فهيد"},
{"国家": "SA","省": "Al-Qassim","城市": "البدايع"},
{"国家": "SA","省": "Al-Qassim","城市": "البكيرية"},
{"国家": "SA","省": "Al-Qassim","城市": "بريدة"},
{"国家": "SA","省": "Al-Qassim","城市": "الدرعية"},
{"国家": "SA","省": "Al-Qassim","城市": "ضليع رشيد"},
{"国家": "SA","省": "Al-Qassim","城市": "بريدة"},
{"国家": "SA","省": "Al-Qassim","城市": "القوارة"},
{"国家": "SA","省": "Al-Qassim","城市": "المذنب"},
{"国家": "SA","省": "Al-Qassim","城市": "المذنب"},
{"国家": "SA","省": "Al-Qassim","城市": "عنيزة"},
{"国家": "SA","省": "Al-Qassim","城市": "عيون الجواء"},
{"国家": "SA","省": "Al-Qassim","城市": "قصيباء"},
{"国家": "SA","省": "Al-Qassim","城市": "رياض الخبراء"},
{"国家": "SA","省": "Al-Qassim","城市": "ساجر"},
{"国家": "SA","省": "Al-Qassim","城市": "ساق"},
{"国家": "SA","省": "Al-Qassim","城市": "عقلة الصقور"},
{"国家": "SA","省": "Al-Riyadh","城市": "عفيف"},
{"国家": "SA","省": "Al-Riyadh","城市": "ليلى"},
{"国家": "SA","省": "Al-Riyadh","城市": "عرجاء"},
{"国家": "SA","省": "Al-Riyadh","城市": "القرين"},
{"国家": "SA","省": "Al-Riyadh","城市": "الغاط"},
{"国家": "SA","省": "Al-Riyadh","城市": "نفي"},
{"国家": "SA","省": "Al-Riyadh","城市": "الارطاوية"},
{"国家": "SA","省": "Al-Riyadh","城市": "منطقة الرياض"},
{"国家": "SA","省": "Al-Riyadh","城市": "الشرائع"},
{"国家": "SA","省": "Al-Riyadh","城市": "الدلم"},
{"国家": "SA","省": "Al-Riyadh","城市": "الدوادمي"},
{"国家": "SA","省": "Al-Riyadh","城市": "درآب"},
{"国家": "SA","省": "Al-Riyadh","城市": "الدرعية"},
{"国家": "SA","省": "Al-Riyadh","城市": "ضرما"},
{"国家": "SA","省": "Al-Riyadh","城市": "الحريق"},
{"国家": "SA","省": "Al-Riyadh","城市": "حوطة بني تميم"},
{"国家": "SA","省": "Al-Riyadh","城市": "حوطة سدير"},
{"国家": "SA","省": "Al-Riyadh","城市": "حريملاء"},
{"国家": "SA","省": "Al-Riyadh","城市": "جلاجل"},
{"国家": "SA","省": "Al-Riyadh","城市": "الخماسين"},
{"国家": "SA","省": "Al-Riyadh","城市": "الخرج"},
{"国家": "SA","省": "Al-Riyadh","城市": "ليلى"},
{"国家": "SA","省": "Al-Riyadh","城市": "المجمعة"},
{"国家": "SA","省": "Al-Riyadh","城市": "مرات"},
{"国家": "SA","省": "Al-Riyadh","城市": "المزاحمية"},
{"国家": "SA","省": "Al-Riyadh","城市": "العيينة"},
{"国家": "SA","省": "Al-Riyadh","城市": "القصب"},
{"国家": "SA","省": "Al-Riyadh","城市": "القويعية"},
{"国家": "SA","省": "Al-Riyadh","城市": "رماح"},
{"国家": "SA","省": "Al-Riyadh","城市": "الرياض"},
{"国家": "SA","省": "Al-Riyadh","城市": "روضة سدير"},
{"国家": "SA","省": "Al-Riyadh","城市": "الرويضة"},
{"国家": "SA","省": "Al-Riyadh","城市": "الصحنة"},
{"国家": "SA","省": "Al-Riyadh","城市": "ساجر"},
{"国家": "SA","省": "Al-Riyadh","城市": "صلبوخ"},
{"国家": "SA","省": "Al-Riyadh","城市": "شقراء"},
{"国家": "SA","省": "Al-Riyadh","城市": " الصريفبع"},
{"国家": "SA","省": "Al-Riyadh","城市": "التنومه"},
{"国家": "SA","省": "Al-Riyadh","城市": "الدرعية"},
{"国家": "SA","省": "Al-Riyadh","城市": "ثادق"},
{"国家": "SA","省": "Al-Riyadh","城市": "ثرمداء"},
{"国家": "SA","省": "Al-Riyadh","城市": "تمير"},
{"国家": "SA","省": "Al-Riyadh","城市": "ام الجماجم"},
{"国家": "SA","省": "Al-Riyadh","城市": "أشيقر"},
{"国家": "SA","省": "Al-Riyadh","城市": "وادي الدواسر"},
{"国家": "SA","省": "Al-Riyadh","城市": "الزلفي"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "منطقة عسير"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "بيشة"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "أبها"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "أحد رفيدة"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "بلحمر"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "بللسمر"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "بارق"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "ظهران الجنوب"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "الحراجه"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "القرعاء"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "خميس مشيط"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "المجاردة"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "محايل"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "النماص"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "رجال ألمع"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "منطقة عسير"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "سراة عبيدة"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "تنومة"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "تثليث"},
{"国家": "SA","省": "Asir{ Aseer}","城市": "الواديين"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "البطحاء"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "حفر الباطن"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الهفوف"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الخفجي"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الخبر"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "النعيرية"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "بقيق"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "عين دار الجديدة"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "   الأحساء"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "عنك"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "أناك"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "العوامية"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "بقيق"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الدمام"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الظهران"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "حرض"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الحوية"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "مدينة الجفر"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الجبيل"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الدمام"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "المبرز"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "مليجة"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "سيهات‎"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الشعبة"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "صفوى"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "العثمانية"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "القارة"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "قرية العليا"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "القطيف"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "القيصومة"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "رأس تنورة"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "راس الخير"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "رأس تنورة"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "روضة هباس"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "السفانية"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "صفوى"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "سلوى"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الصرّار"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الجبيل"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "سيهات‎"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "تناجيب"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "تاروت"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "الخبر"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "العضيلية"},
{"国家": "SA","省": "Eastern Region {Ash-Sharqiyah}","城市": "العيون"},
{"国家": "SA","省": "Hail","城市": "الأجفر"},
{"国家": "SA","省": "Hail","城市": "الحائط"},
{"国家": "SA","省": "Hail","城市": "حايل"},
{"国家": "SA","省": "Hail","城市": "حايل"},
{"国家": "SA","省": "Hail","城市": "الشملي"},
{"国家": "SA","省": "Hail","城市": "الشنان"},
{"国家": "SA","省": "Hail","城市": "بقعاء"},
{"国家": "SA","省": "Hail","城市": "بقعاء"},
{"国家": "SA","省": "Hail","城市": "الغزالة"},
{"国家": "SA","省": "Hail","城市": "حايل"},
{"国家": "SA","省": "Hail","城市": "موقق"},
{"国家": "SA","省": "Hail","城市": "موقق"},
{"国家": "SA","省": "Hail","城市": "القاعد"},
{"国家": "SA","省": "Hail","城市": "قفار"},
{"国家": "SA","省": "Hail","城市": "حايل"},
{"国家": "SA","省": "Hail","城市": "الشنان"},
{"国家": "SA","省": "Hail","城市": "سميراء"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "جازان"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "أبو عريش"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "احد المسارحة"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "العارضة"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "العيدابي"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "بيش"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "ضمد"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "الدرب"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "فرسان"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "جيزان"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "الكربوس"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "الخشابية"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "صبيا"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "صامطة"},
{"国家": "SA","省": "Jizan{Gizan}","城市": "الظبية"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الهدا"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "عمق"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "عسفان"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "مكة المكرمة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الشقيق"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "بحرة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "بحرة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "البرك"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "ذهبان"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الطائف"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الجعرانة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "جدة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الجموم"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "خليص"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الخرمة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الليث"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "مكه"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "مستورة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "المظيلف"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "نمرة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "النوارية"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "القحمة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "القنفذة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "رابغ"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "رنيه"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الشعيبة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الشرائع"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الشميسي"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "طيبة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "الطائف"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "ثول"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "التربة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "جدة"},
{"国家": "SA","省": "Makkah{Mecca}","城市": "ذهبان"},
{"国家": "SA","省": "Najran","城市": "نجران"},
{"国家": "SA","省": "Najran","城市": "شرورة"},
{"国家": "SA","省": "Northern Borders {Al-Hudud ash-Shamaliyah}","城市": "رفحاء"},
{"国家": "SA","省": "Northern Borders {Al-Hudud ash-Shamaliyah}","城市": "عرعر"},
{"国家": "SA","省": "Northern Borders {Al-Hudud ash-Shamaliyah}","城市": "حازم الجلاميد"},
{"国家": "SA","省": "Northern Borders {Al-Hudud ash-Shamaliyah}","城市": "طريف"},
{"国家": "SA","省": "Tabuk","城市": "البدع"},
{"国家": "SA","省": "Tabuk","城市": "ضباء"},
{"国家": "SA","省": "Tabuk","城市": "حالة عمار"},
{"国家": "SA","省": "Tabuk","城市": "حقل"},
{"国家": "SA","省": "Tabuk","城市": "تبوك"},
{"国家": "SA","省": "Tabuk","城市": "تيماء"},
{"国家": "SA","省": "Tabuk","城市": "أملج"},
{"国家": "SA","省": "Tabuk","城市": "الوجه"},


  









{"国家": "KW","省": "Hawally","城市": "Al-Bidea"},
{"国家": "KW","省": "Hawally","城市": "Al-Siddeeq"},
{"国家": "KW","省": "Hawally","城市": "Anjafa"},
{"国家": "KW","省": "Hawally","城市": "Bayan"},
{"国家": "KW","省": "Hawally","城市": "Hateen"},
{"国家": "KW","省": "Hawally","城市": "Hawally"},
{"国家": "KW","省": "Hawally","城市": "Jabriya"},
{"国家": "KW","省": "Hawally","城市": "Maidan Hawally"},
{"国家": "KW","省": "Hawally","城市": "Mishref"},
{"国家": "KW","省": "Hawally","城市": "Mubarak Al-Abdullah"},
{"国家": "KW","省": "Hawally","城市": "Rumaithiya"},
{"国家": "KW","省": "Hawally","城市": "Salam"},
{"国家": "KW","省": "Hawally","城市": "Salmiya"},
{"国家": "KW","省": "Hawally","城市": "Salwa"},
{"国家": "KW","省": "Hawally","城市": "Shaab"},
{"国家": "KW","省": "Hawally","城市": "Shuhada"},
{"国家": "KW","省": "Hawally","城市": "Zahra"},
{"国家": "KW","省": "Farwaniya","城市": "Abbasiya"},
{"国家": "KW","省": "Farwaniya","城市": "Abdullah Al Mubarak Al Sabah"},
{"国家": "KW","省": "Farwaniya","城市": "Abraq Khaitan"},
{"国家": "KW","省": "Farwaniya","城市": "Al-Dajeej"},
{"国家": "KW","省": "Farwaniya","城市": "Al-Shadadiya"},
{"国家": "KW","省": "Farwaniya","城市": "Andalous"},
{"国家": "KW","省": "Farwaniya","城市": "Ardiya"},
{"国家": "KW","省": "Farwaniya","城市": "Ardiya Small Industrial"},
{"国家": "KW","省": "Farwaniya","城市": "Ardiya Storage Zone"},
{"国家": "KW","省": "Farwaniya","城市": "Doha"},
{"国家": "KW","省": "Farwaniya","城市": "Farwaniyah"},
{"国家": "KW","省": "Farwaniya","城市": "Firdous"},
{"国家": "KW","省": "Farwaniya","城市": "Ishbiliya"},
{"国家": "KW","省": "Farwaniya","城市": "Jeleeb Al-Shuyoukh"},
{"国家": "KW","省": "Farwaniya","城市": "Khaitan"},
{"国家": "KW","省": "Farwaniya","城市": "Kuwait International Airport"},
{"国家": "KW","省": "Farwaniya","城市": "Omariya"},
{"国家": "KW","省": "Farwaniya","城市": "Rabia"},
{"国家": "KW","省": "Farwaniya","城市": "Rai"},
{"国家": "KW","省": "Farwaniya","城市": "Rehab"},
{"国家": "KW","省": "Farwaniya","城市": "Rigai"},
{"国家": "KW","省": "Farwaniya","城市": "Sabah Al Nasser"},
{"国家": "KW","省": "Farwaniya","城市": "Sheikh Saad Aviation Terminal"},
{"国家": "KW","省": "Farwaniya","城市": "South Khaitan-Exhibits"},
{"国家": "KW","省": "Ahmadi","城市": "Abu Halifa"},
{"国家": "KW","省": "Ahmadi","城市": "Ahmadi"},
{"国家": "KW","省": "Ahmadi","城市": "Al Khiran"},
{"国家": "KW","省": "Ahmadi","城市": "Al Wafrah"},
{"国家": "KW","省": "Ahmadi","城市": "Al-Julaia'a"},
{"国家": "KW","省": "Ahmadi","城市": "Al-Nuwaiseeb"},
{"国家": "KW","省": "Ahmadi","城市": "Al-Riqqa"},
{"国家": "KW","省": "Ahmadi","城市": "Ali Sabah Al Salem"},
{"国家": "KW","省": "Ahmadi","城市": "Assabahiyah"},
{"国家": "KW","省": "Ahmadi","城市": "Bnaider"},
{"国家": "KW","省": "Ahmadi","城市": "Dahar"},
{"国家": "KW","省": "Ahmadi","城市": "Eqaila"},
{"国家": "KW","省": "Ahmadi","城市": "Fahad Al Ahmad"},
{"国家": "KW","省": "Ahmadi","城市": "Fahaheel"},
{"国家": "KW","省": "Ahmadi","城市": "Fintas"},
{"国家": "KW","省": "Ahmadi","城市": "Hadiya"},
{"国家": "KW","省": "Ahmadi","城市": "Jaber Al Ali"},
{"国家": "KW","省": "Ahmadi","城市": "Mahboula"},
{"国家": "KW","省": "Ahmadi","城市": "Mangaf"},
{"国家": "KW","省": "Ahmadi","城市": "Sabah Al Ahmad"},
{"国家": "KW","省": "Ahmadi","城市": "Shalayhat Al Dubaiya"},
{"国家": "KW","省": "Ahmadi","城市": "Shalayhat Mina Abdullah"},
{"国家": "KW","省": "Ahmadi","城市": "Shuaiba Block 1"},
{"国家": "KW","省": "Ahmadi","城市": "West Industrial Shuaiba"},
{"国家": "KW","省": "Ahmadi","城市": "Zour"},
{"国家": "KW","省": "Kuwait City","城市": "Abdullah al-Salem"},
{"国家": "KW","省": "Kuwait City","城市": "Adailiya"},
{"国家": "KW","省": "Kuwait City","城市": "Bneid Al Qar"},
{"国家": "KW","省": "Kuwait City","城市": "Daiya"},
{"国家": "KW","省": "Kuwait City","城市": "Dasma"},
{"国家": "KW","省": "Kuwait City","城市": "Dasman"},
{"国家": "KW","省": "Kuwait City","城市": "Faiha"},
{"国家": "KW","省": "Kuwait City","城市": "Granada"},
{"国家": "KW","省": "Kuwait City","城市": "Jaber Al Ahmad"},
{"国家": "KW","省": "Kuwait City","城市": "Jibla"},
{"国家": "KW","省": "Kuwait City","城市": "Kaifan"},
{"国家": "KW","省": "Kuwait City","城市": "Khaldiya"},
{"国家": "KW","省": "Kuwait City","城市": "Kuwait City"},
{"国家": "KW","省": "Kuwait City","城市": "Kuwait Free Trade Zone"},
{"国家": "KW","省": "Kuwait City","城市": "Mansouriya"},
{"国家": "KW","省": "Kuwait City","城市": "Mirqab"},
{"国家": "KW","省": "Kuwait City","城市": "Nahdha"},
{"国家": "KW","省": "Kuwait City","城市": "North West Al-Sulaibikhat"},
{"国家": "KW","省": "Kuwait City","城市": "Nuzha"},
{"国家": "KW","省": "Kuwait City","城市": "Qadsiya"},
{"国家": "KW","省": "Kuwait City","城市": "Qairawan"},
{"国家": "KW","省": "Kuwait City","城市": "Qortuba"},
{"国家": "KW","省": "Kuwait City","城市": "Rawda"},
{"国家": "KW","省": "Kuwait City","城市": "Salhiya"},
{"国家": "KW","省": "Kuwait City","城市": "Shamiya"},
{"国家": "KW","省": "Kuwait City","城市": "Sharq"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Administrative"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Industrial"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Industrial 1"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Industrial 2"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Industrial 3"},
{"国家": "KW","省": "Kuwait City","城市": "Shuwaikh Residential"},
{"国家": "KW","省": "Kuwait City","城市": "Souk Al Mubarakeya"},
{"国家": "KW","省": "Kuwait City","城市": "Sulaibikhat"},
{"国家": "KW","省": "Kuwait City","城市": "Surra"},
{"国家": "KW","省": "Kuwait City","城市": "Yarmouk"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Abu Al Hasaniya"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Abu Fatira"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Adan"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Al-Masayel"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Fnaitees"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Messila"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Mubarak Al Kabeer"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Qurain"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Qusor"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Sabah Al Salem"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Sabhan Industrial Area"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "South Wista"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "West of Abu Fatira Al-Herafia"},
{"国家": "KW","省": "Mubarak Al Kabir","城市": "Wista"},
{"国家": "KW","省": "Jahra","城市": "Al Sulaibiya Industrial 1"},
{"国家": "KW","省": "Jahra","城市": "Al Sulaibiya Industrial 2"},
{"国家": "KW","省": "Jahra","城市": "Amgarah Industrial Area"},
{"国家": "KW","省": "Jahra","城市": "Jahra"},
{"国家": "KW","省": "Jahra","城市": "Naeem"},
{"国家": "KW","省": "Jahra","城市": "Naseem"},
{"国家": "KW","省": "Jahra","城市": "Oyoun"},
{"国家": "KW","省": "Jahra","城市": "Qasr"},
{"国家": "KW","省": "Jahra","城市": "Saad Al Abdullah"},
{"国家": "KW","省": "Jahra","城市": "Sulaibiya"},
{"国家": "KW","省": "Jahra","城市": "Taima'"},
{"国家": "KW","省": "Jahra","城市": "Waha"},







{"国家": "OM","省": "Oman","城市": "روي"},
{"国家": "OM","省": "Oman","城市": "عامرات"},
{"国家": "OM","省": "Oman","城市": "وادي كابير"},
{"国家": "OM","省": "Oman","城市": "موالح"},
{"国家": "OM","省": "Oman","城市": "غلا"},
{"国家": "OM","省": "Oman","城市": "الحمرية"},
{"国家": "OM","省": "Oman","城市": "سيداب"},
{"国家": "OM","省": "Oman","城市": "الخضرة"},
{"国家": "OM","省": "Oman","城市": "الرصيف"},
{"国家": "OM","省": "Oman","城市": "مدينة سلطان قابوس"},
{"国家": "OM","省": "Oman","城市": "بوشير"},
{"国家": "OM","省": "Oman","城市": "مسقط"},
{"国家": "OM","省": "Oman","城市": "Azaiba"},
{"国家": "OM","省": "Oman","城市": "العوابي - مسقط"},
{"国家": "OM","省": "Oman","城市": "الخوير"},
{"国家": "OM","省": "Oman","城市": "القرم"},
{"国家": "OM","省": "Oman","城市": "مطرح"},
{"国家": "OM","省": "Oman","城市": "سيف"},
{"国家": "OM","省": "Oman","城市": "غبرة"},
{"国家": "OM","省": "Oman","城市": "وادي أداي"},
{"国家": "OM","省": "Oman","城市": "جيبرو"},
{"国家": "OM","省": "Oman","城市": "واطيا"},
{"国家": "OM","省": "Oman","城市": "العوابي - بركاء"},
{"国家": "OM","省": "Oman","城市": "الدقم"},
{"国家": "OM","省": "Oman","城市": "الحمراء"},
{"国家": "OM","省": "Oman","城市": "الغزال"},
{"国家": "OM","省": "Oman","城市": "الكابيل"},
{"国家": "OM","省": "Oman","城市": "الكاميل وول وافي"},
{"国家": "OM","省": "Oman","城市": "المضيبعي"},
{"国家": "OM","省": "Oman","城市": "Sunaina"},
{"国家": "OM","省": "Oman","城市": "Yankul"},
{"国家": "OM","省": "Oman","城市": "بهلاء"},
{"国家": "OM","省": "Oman","城市": "بركة"},
{"国家": "OM","省": "Oman","城市": "بيدبد"},
{"国家": "OM","省": "Oman","城市": "البضلة"},
{"国家": "OM","省": "Oman","城市": "بيديا"},
{"国家": "OM","省": "Oman","城市": "البريمي"},
{"国家": "OM","省": "Oman","城市": "ضانك"},
{"国家": "OM","省": "Oman","城市": "ديبا"},
{"国家": "OM","省": "Oman","城市": "فلج القبل .."},
{"国家": "OM","省": "Oman","城市": "صحار"},
{"国家": "OM","省": "Oman","城市": "فانجا"},
{"国家": "OM","省": "Oman","城市": "إبرا"},
{"国家": "OM","省": "Oman","城市": "Ibri"},
{"国家": "OM","省": "Oman","城市": "Izki"},
{"国家": "OM","省": "Oman","城市": "جالان بني بو علي"},
{"国家": "OM","省": "Oman","城市": "جالان ني بو حسن"},
{"国家": "OM","省": "Oman","城市": "خابورة"},
{"国家": "OM","省": "Oman","城市": "ليوا"},
{"国家": "OM","省": "Oman","城市": "مادها"},
{"国家": "OM","省": "Oman","城市": "ماناه"},
{"国家": "OM","省": "Oman","城市": "مصيرة"},
{"国家": "OM","省": "Oman","城市": "Musannah"},
{"国家": "OM","省": "Oman","城市": "Nakhl"},
{"国家": "OM","省": "Oman","城市": "نيزوا"},
{"国家": "OM","省": "Oman","城市": "القريات"},
{"国家": "OM","省": "Oman","城市": "الرستاق"},
{"国家": "OM","省": "Oman","城市": "صحم"},
{"国家": "OM","省": "Oman","城市": "صلالة"},
{"国家": "OM","省": "Oman","城市": "سمايل"},
{"国家": "OM","省": "Oman","城市": "شناص"},
{"国家": "OM","省": "Oman","城市": "سور"},
{"国家": "OM","省": "Oman","城市": "السويق"},










  ]